version: '3'

services:
  # Vue Client
  client-node:
    container_name: client-node
    restart: always
    build:
      context: ./www/vue_client
      dockerfile: Dockerfile
    ports:
      - "5172:5172"
    depends_on:
      - server-node
    networks:
      - app-network
    # command: sh -c "npm run build && npm run preview"

  # Node Server
  server-node:
    container_name: server-node
    restart: always
    build:
      context: ./www/node_server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./www/node_server:/app
    networks:
      - app-network

  # Lumen Server
  lumen-server:
    container_name: "lumen-server"
    restart: always
    build:
      context: ./www/lumen_server
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    command: php -S 0.0.0.0:8000 -t public
  
  # Database PostgreSQL
  postgres-db:
    image: postgres:latest
    container_name: "postgres_node"
    restart: always
    ports:
      - "5431:5432"
    environment:
      # POSTGRES_DB: crud_node
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      # - postgres-data:/var/lib/postgresql/data
      - ./db/postgresql/data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge